# Generated by Django 5.2.8 on 2025-12-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='model',
            field=models.CharField(choices=[('claude-sonnet-4-5', 'Claude 4.5 Sonnet'), ('claude-opus-4', 'Claude 4 Opus'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('claude-3-opus-20240229', 'Claude 3 Opus'), ('claude-3-haiku-20240307', 'Claude 3 Haiku')], default='claude-sonnet-4-5', max_length=50),
        ),
    ]
