# Generated by Django 5.2.8 on 2025-12-01 18:34

import django.db.models.deletion
from django.db import migrations, models


def migrate_single_to_multi_model(apps, schema_editor):
    """Convert single model field to selected_models array"""
    Conversation = apps.get_model('chat', 'Conversation')
    for conversation in Conversation.objects.all():
        if conversation.model:
            conversation.selected_models = [conversation.model]
            conversation.save(update_fields=['selected_models'])


def reverse_migrate(apps, schema_editor):
    """Reverse: Convert selected_models array back to single model"""
    Conversation = apps.get_model('chat', 'Conversation')
    for conversation in Conversation.objects.all():
        if conversation.selected_models and len(conversation.selected_models) > 0:
            conversation.model = conversation.selected_models[0]
            conversation.save(update_fields=['model'])


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_model'),
    ]

    operations = [
        # Add selected_models field first (before removing model)
        migrations.AddField(
            model_name='conversation',
            name='selected_models',
            field=models.JSONField(default=list),
        ),
        # Migrate data from model to selected_models
        migrations.RunPython(migrate_single_to_multi_model, reverse_migrate),
        # Remove old model field
        migrations.RemoveField(
            model_name='conversation',
            name='model',
        ),
        # Add new Message fields
        migrations.AddField(
            model_name='message',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_responses', to='chat.message'),
        ),
    ]
