# Generated by Django 5.2.8 on 2025-12-01 18:46

from django.db import migrations


def fix_invalid_model_ids(apps, schema_editor):
    """Fix invalid model IDs in existing conversations and messages"""
    Conversation = apps.get_model('chat', 'Conversation')
    Message = apps.get_model('chat', 'Message')

    # Mapping of old invalid IDs to correct ones
    model_id_mapping = {
        'claude-sonnet-4-5': 'claude-3-5-sonnet-20241022',
        'claude-opus-4': 'claude-3-opus-20240229',
    }

    # Fix conversations
    for conversation in Conversation.objects.all():
        if isinstance(conversation.selected_models, list):
            updated = False
            new_models = []
            for model_id in conversation.selected_models:
                if model_id in model_id_mapping:
                    new_models.append(model_id_mapping[model_id])
                    updated = True
                else:
                    new_models.append(model_id)

            if updated:
                conversation.selected_models = new_models
                conversation.save(update_fields=['selected_models'])

    # Fix messages
    for message in Message.objects.filter(model__isnull=False):
        if message.model in model_id_mapping:
            message.model = model_id_mapping[message.model]
            message.save(update_fields=['model'])


def reverse_fix(apps, schema_editor):
    """Reverse migration - map back to old IDs"""
    Conversation = apps.get_model('chat', 'Conversation')
    Message = apps.get_model('chat', 'Message')

    # Reverse mapping
    reverse_mapping = {
        'claude-3-5-sonnet-20241022': 'claude-sonnet-4-5',
        'claude-3-opus-20240229': 'claude-opus-4',
    }

    # Fix conversations
    for conversation in Conversation.objects.all():
        if isinstance(conversation.selected_models, list):
            updated = False
            new_models = []
            for model_id in conversation.selected_models:
                if model_id in reverse_mapping:
                    new_models.append(reverse_mapping[model_id])
                    updated = True
                else:
                    new_models.append(model_id)

            if updated:
                conversation.selected_models = new_models
                conversation.save(update_fields=['selected_models'])

    # Fix messages
    for message in Message.objects.filter(model__isnull=False):
        if message.model in reverse_mapping:
            message.model = reverse_mapping[message.model]
            message.save(update_fields=['model'])


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_conversation_model_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_invalid_model_ids, reverse_fix),
    ]
